services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ct_db
    environment:
      POSTGRES_DB: copiloto
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d copiloto"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ct_ollama
    ports: ["11434:11434"]
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD","ollama","--version"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
volumes:
  pg_data:
  ollama_data:
